### ISSUE TITLE
target directory not ignored by git

### ISSUE THREAD

**Issue by exsilium** [gronet/comcybtask#3]
Suggestion - add `target` directory to git ignore as it pollutes the status state.

**Comment by gronet** [comment]
I cannot fix issue because do not understand what means "it pollutes the status state". Please specify.

**Comment by exsilium** [comment]
I seee you added a `.gitignore` and addressed the issue. The status state pollution is meant that if you do not add compile time artifacts to git status, it will distract you when monitoring for changes with `git status`. Anyways, the original comment was addressed. Thanks!
