### ISSUE TITLE
File names are not in camel case

### ISSUE THREAD

**Issue by dynamics3** [gronet/comcybtask#4]
It is possible to get an overview of Kotlin code conventions here: [https://kotlinlang.org/docs/reference/coding-conventions.html](url)

**Comment by exsilium** [comment]
In fact, I would recommend to implement a linter of some kind - e.g. a `ktlint` or `prettier` ( https://ktlint.github.io/ && https://prettier.io/ ) to test against conventions.

**Comment by gronet** [comment]
Files are renamed. I will look at lint tools to improve quality.
